# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0  # or specific git tag
    hooks:
      - id: shellcheck    # Lints shell scripts, see https://www.shellcheck.net/
      - id: shfmt         # Auto formats shell scripts, see https://github.com/patrickvane/shfmt
      - id: markdownlint  # Lint markdown files, see https://github.com/markdownlint/markdownlint

# Ensure that the project at least compiles and source code is formatted to standards
  - repo: https://github.com/ejba/pre-commit-maven
    rev: v0.3.3
    hooks:
      - id: maven
        args: [ 'clean compile' ]
      - id: maven-spotless-apply

 # sqlfluff lints the sql files, no auto fixing
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.1.4
    hooks:
      - id: sqlfluff-lint
