# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict

  # Markdown linting is configured using .mdlrc and .mdl_style.rb
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0  # or specific git tag
    hooks:
      - id: shellcheck    # Lints shell scripts, see https://www.shellcheck.net/
        exclude: 'mvnw'   # Exclude maven wrapper script, because it is provided by a 3rd party
      - id: markdownlint  # Lint markdown files, see https://github.com/markdownlint/markdownlint
        args: ['-c', '.mdlrc']

  # Ensure that source code is formatted to standards when committing
  - repo: https://github.com/ejba/pre-commit-maven
    rev: v0.3.3
    hooks:
      - id: maven-spotless-apply

 # sqlfluff lints the sql files, no auto fixing
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.1.4
    hooks:
      - id: sqlfluff-lint

  # enforcing conventional commits
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
