# FIXME: use a eurodata interally accessible URL once the ruleset is published
extends:
  - https://raw.githubusercontent.com/rattermeyer/spectral-ruleset/v0.8.0/eurodata.yml

formats: [oas3]

rules: {}
