[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
////
Describes the relevant requirements and the driving forces that software architects and development team must consider.
These include

* underlying business goals,
* essential features,
* essential functional requirements,
* quality goals for the architecture and
* relevant stakeholders and their expectations
////

This document tries to establish a common solution architecture proposal that addresses the laid-out Enterprise Architecture goals and at the same time
allowing enough freedom to address the specific needs of different products within eurodata.

The solution architecture should support the following architecture principles:

* Design for Change: Die Organisation muss mit sich schnell ändernden Anforderungen umgehen können, und alle Produkte müssen so gestaltet sein, dass Anforderungsänderungen so einfach wie möglich umsetzbar sind.
* Reuse Before Build: Vor der Entwicklung neuer Komponenten wird geprüft, ob ähnliche Komponenten bereits in anderen Produkten bestehen, und ob eine gemeinschaftliche Entwicklung sinnvoll wäre.
* Standardized Technology Stack: Die Verwendung von Komponenten außerhalb des standardisierten Technology Stacks muss begründet und dokumentiert werden („ADR“, Architecture Decision Record)
* Modules Over Monolith: Produkte werden in allen Aspekten modularisiert aufgebaut (Benutzerschnittstelle, Backend-Logik, Datenbank), so dass jedes Modul einem eigenen Team zugeordnet und unabhängig von anderen Modulen weiterentwickelt werden kann.
* Central Architecture Governance: Architekturentscheidungen werden zentral vorgestellt, Abweichungen von Leitlinien werden begründet und dokumentiert (ADR)

=== Requirements Overview

=== Quality Goals

=== Stakeholders

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Role-1>_ | _<Contact-1>_ | _<Expectation-1>_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
