[[section-system-scope-and-context]]
== System Scope and Context

=== Business Context

The business context is special to every eurodata product.
Therefore, we do not show anything here.

////
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally,) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

////

**<Diagram or Table>**

**<optionally: Explanation of external domain interfaces>**

=== Technical Context

The technical context may also vary between different eurodata products.

[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation which I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

[plantuml]
----
include::example$technical-context.puml[]
----

**<Diagram or Table>**

[cols="1,3"]
|===
|Element | Description

|Tax Office User
|

|Office AddIn
|

|Web Browser
|

|Partner Product
|

|the product
|This is the product we are developing
// {TODO}: rename it to the real product name

|another ed product
|Representative for other ed products used
// Repeat for every product used

|yet another ed product
|Proxy for other ed products that consume services our product offers
// Repeat for every product used

|shared services
|Shared services within ed that are used

|elastic platform
|ed platform of choice for log management and APM.

|Prometheus
|collects metrics from various systems and maintains a time-series database

|Keycloak
|The identity and access management system that also provides an OAuth 2.0 authorization server with OIDC support.



|===



**<optionally: Explanation of technical interfaces>**

**<Mapping Input/Output to Channels>**
